<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Marten" Version="[9.21.0,10.0.0)" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Stores" Version="[10.0.10,11.0.0)" />
    <PackageVersion Include="Npgsql" Version="[9.0.4,10.0.0)"
                    Condition="'$(MSBuildProjectName)' == 'Innovorium.OpenIddict.Marten'" />
    <PackageVersion Include="OpenIddict.Core" Version="[7.6.0,8.0.0)" />
    <PackageVersion Include="Weasel.Storage" Version="[9.17.0,10.0.0)"
                    Condition="'$(MSBuildProjectName)' == 'Innovorium.OpenIddict.Marten'" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
  </ItemGroup>
</Project>
